### ISSUE TITLE
出现ReferenceError: require is not defined

### ISSUE THREAD

**Issue by wuye999** [NXY666/JsjiamiV6-Decryptor#1]
![image](https://user-images.githubusercontent.com/79479594/148268347-1c76035a-09e8-45cd-8cd5-3ffb316724a2.png)

**Comment by NXY666** [comment]
检查一下nodejs有没有配置正确

**Comment by NXY666** [comment]
可能是加密的JS文件不支持，目前只支持解密选择“autoJS”模式的脚本

**Comment by wuye999** [comment]
> 

https://github.com/NXY666/JsjiamiV6-Decryptor/issues/1#issuecomment-1005978509
这个是尝试解密运行失败的js文件，大佬看看

**Comment by wuye999** [comment]
> > 
> 
> [#1 (comment)](https://github.com/NXY666/JsjiamiV6-Decryptor/issues/1#issuecomment-1005978509) 这个是尝试解密运行失败的js文件，大佬看看

https://raw.githubusercontent.com/wuye999/aabbccdd/main/aabbccdd.js

**Comment by NXY666** [comment]
啊我懂了，这个JS并不是整个都是用v6加密的
你把var iｉl='jsjiami.com.v6'到['tokenKey']);};;iｉl='jsjiami.com.v6';的那一段单独拿出来试一下

**Comment by wuye999** [comment]
> 啊我懂了，这个JS并不是整个都是用v6加密的 你把var iｉl='jsjiami.com.v6'到['tokenKey']);};;iｉl='jsjiami.com.v6';的那一段单独拿出来试一下

那一段单独拿出来执行成功了，但还是很奇怪，这个执行后生成的文件，接下来该如何进行啊
https://raw.githubusercontent.com/wuye999/aabbccdd/main/encryptEdited1.js

**Comment by wuye999** [comment]
> > 啊我懂了，这个JS并不是整个都是用v6加密的 你把var iｉl='jsjiami.com.v6'到['tokenKey']);};;iｉl='jsjiami.com.v6';的那一段单独拿出来试一下
> 
> 那一段单独拿出来执行成功了，但还是很奇怪，这个执行后生成的文件，接下来该如何进行啊 https://raw.githubusercontent.com/wuye999/aabbccdd/main/encryptEdited1.js

生成的全部文件在这个仓库 https://github.com/wuye999/aabbccdd

**Comment by NXY666** [comment]
> > > 啊我懂了，这个JS并不是整个都是用v6加密的 你把var iｉl='jsjiami.com.v6'到['tokenKey']);};;iｉl='jsjiami.com.v6';的那一段单独拿出来试一下
> > 
> > 
> > 那一段单独拿出来执行成功了，但还是很奇怪，这个执行后生成的文件，接下来该如何进行啊 https://raw.githubusercontent.com/wuye999/aabbccdd/main/encryptEdited1.js
> 
> 生成的全部文件在这个仓库 https://github.com/wuye999/aabbccdd

看起来并没有解密成功，我回头瞧瞧，这几天期末考有点忙。现在这个版本是我随手弄出来的，问题一大堆😂

**Comment by wuye999** [comment]
> 

感谢解答，等大佬考完再看看吧，有进展的话希望通知一下，我的邮箱 2368693074@qq.com

**Comment by NXY666** [comment]
新版本对前半部分代码几乎重写了，你可以再试试。
