### ISSUE TITLE
TQL，已Star！

### ISSUE THREAD

**Issue by yyfgcchjk** [NXY666/JsjiamiV6-Decryptor#10]
大牛，麻烦看下我这个，为啥运行就报错，是个假的v6吗复制这段内容后打开天翼云盘手机App，操作更方便哦！链接：https://cloud.189.cn/t/RJJ7V3FBnIf2

**Comment by NXY666** [comment]
![image](https://user-images.githubusercontent.com/62371554/155889189-ea54ea12-8ad0-455d-86ed-1263f64506e5.png)
不会报错呀😐

**Comment by yyfgcchjk** [comment]
好的，可能我环境错了😣
