### ISSUE TITLE
解析失败

### ISSUE THREAD

**Issue by zhangsanplus** [NXY666/JsjiamiV6-Decryptor#11]
这个文件无法解析 
https://aliyuncs.kuaiyingyong.vip/js/ee1f6cd3effda984.js

**Comment by NXY666** [comment]
第一行有一个回车，去掉试试呢？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月7日(周一) 上午10:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [NXY666/JsjiamiV6-Decryptor] 这个文件解析失败 (Issue #11)




 
https://aliyuncs.kuaiyingyong.vip/js/ee1f6cd3effda984.js
 
&mdash;

**Comment by NXY666** [comment]
我检查了一下，不是说解密失败了，是这个文件有两重加密，你可以解密完后把第二层加密的内容分离出来，删去空格再次解密一遍。
