### ISSUE TITLE
无法解密

### ISSUE THREAD

**Issue by FoxNick** [NXY666/JsjiamiV6-Decryptor#14]
https://jhpc.manduhu.com/duoduo/js/play.js

**Comment by NXY666** [comment]
内有一处块注释，将其删掉后再试一下？

**Comment by FoxNick** [comment]
replaceObjFunc 这个里面的吗 ？好像不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月17日(星期四) 中午1:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14)





 
内有一处块注释，将其删掉后再试一下？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NXY666** [comment]
> replaceObjFunc 这个里面的吗 ？好像不行
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年3月17日(星期四) 中午1:59 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) 内有一处块注释，将其删掉后再试一下？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

不是不是，我是说要解密的代码里面：
![image](https://user-images.githubusercontent.com/62371554/158747200-153bde7c-7ccf-4133-b764-bfa8e296f07e.png)
把注释和回车去掉，保证代码只有一行

**Comment by FoxNick** [comment]
可以解 这种情况 必须这么处理吗？如果不用 node 的VM 模块 普通JS 如何执行 解混淆函数




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月17日(星期四) 下午2:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14)





  
replaceObjFunc 这个里面的吗 ？好像不行
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年3月17日(星期四) 中午1:59 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) 内有一处块注释，将其删掉后再试一下？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
不是不是，我是说要解密的代码里面：
 
 把注释和回车去掉，保证代码只有一行
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NXY666** [comment]
> 可以解 这种情况 必须这么处理吗？如果不用 node 的VM 模块 普通JS 如何执行 解混淆函数
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年3月17日(星期四) 下午2:06 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) replaceObjFunc 这个里面的吗 ？好像不行 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年3月17日(星期四) 中午1:59 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) 内有一处块注释，将其删掉后再试一下？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt; 不是不是，我是说要解密的代码里面： 把注释和回车去掉，保证代码只有一行 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我有想做一个去除中间注释的，但是这玩意并不简单。所以现在只能手动去掉。
vm模块是虚拟机，但是实际上是有办法跳出虚拟机的。网上有一些比较安全的第三方虚拟机比如说vm2，只要重写virtualGlobalEval()函数，输入的是js字符串，return运行结果，然后保证每次执行用的同一个context就行了。

**Comment by FoxNick** [comment]
有兴趣 加个QQ 吗 354435383




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月17日(星期四) 下午2:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14)





  
可以解 这种情况 必须这么处理吗？如果不用 node 的VM 模块 普通JS 如何执行 解混淆函数
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年3月17日(星期四) 下午2:06 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) replaceObjFunc 这个里面的吗 ？好像不行 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年3月17日(星期四) 中午1:59 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) 内有一处块注释，将其删掉后再试一下？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 不是不是，我是说要解密的代码里面： 把注释和回车去掉，保证代码只有一行 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt;
  
我有想做一个去除中间注释的，但是这玩意并不简单。所以现在只能手动去掉。
 vm模块是虚拟机，但是实际上是有办法跳出虚拟机的。网上有一些比较安全的第三方虚拟机比如说vm2，只要重写virtualGlobalEval()函数，输入的是js字符串，return运行结果，然后保证每次执行用的同一个context就行了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FoxNick** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NXY666/JsjiamiV6-Decryptor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月17日(星期四) 下午2:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14)





  
可以解 这种情况 必须这么处理吗？如果不用 node 的VM 模块 普通JS 如何执行 解混淆函数
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年3月17日(星期四) 下午2:06 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) replaceObjFunc 这个里面的吗 ？好像不行 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年3月17日(星期四) 中午1:59 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) 内有一处块注释，将其删掉后再试一下？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 不是不是，我是说要解密的代码里面： 把注释和回车去掉，保证代码只有一行 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt;
  
我有想做一个去除中间注释的，但是这玩意并不简单。所以现在只能手动去掉。
 vm模块是虚拟机，但是实际上是有办法跳出虚拟机的。网上有一些比较安全的第三方虚拟机比如说vm2，只要重写virtualGlobalEval()函数，输入的是js字符串，return运行结果，然后保证每次执行用的同一个context就行了。
 
—




可以尝试 使用&nbsp;jQuery.globalEval


Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FoxNick** [comment]
var globalEval = eval;&nbsp; &nbsp; &nbsp;//定义全局eval函数别名
function virtualGlobalEval ( data ) {
&nbsp; &nbsp; &nbsp; return globalEval(data);
&nbsp; &nbsp; }



这样 就能解




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NXY666/JsjiamiV6-Decryptor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月17日(星期四) 下午2:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14)





  
可以解 这种情况 必须这么处理吗？如果不用 node 的VM 模块 普通JS 如何执行 解混淆函数
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年3月17日(星期四) 下午2:06 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) replaceObjFunc 这个里面的吗 ？好像不行 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年3月17日(星期四) 中午1:59 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) 内有一处块注释，将其删掉后再试一下？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 不是不是，我是说要解密的代码里面： 把注释和回车去掉，保证代码只有一行 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt;
  
我有想做一个去除中间注释的，但是这玩意并不简单。所以现在只能手动去掉。
 vm模块是虚拟机，但是实际上是有办法跳出虚拟机的。网上有一些比较安全的第三方虚拟机比如说vm2，只要重写virtualGlobalEval()函数，输入的是js字符串，return运行结果，然后保证每次执行用的同一个context就行了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NXY666** [comment]
> var globalEval = eval;&nbsp; &nbsp; &nbsp;//定义全局eval函数别名
> function virtualGlobalEval ( data ) {
> &nbsp; &nbsp; &nbsp; return globalEval(data);
> &nbsp; &nbsp; }
> 
> 
> 
> 这样 就能解
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "NXY666/JsjiamiV6-Decryptor"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2022年3月17日(星期四) 下午2:19
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14)
> 
> 
> 
> 
> 
>   
> 可以解 这种情况 必须这么处理吗？如果不用 node 的VM 模块 普通JS 如何执行 解混淆函数
>  …
>  ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年3月17日(星期四) 下午2:06 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) replaceObjFunc 这个里面的吗 ？好像不行 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年3月17日(星期四) 中午1:59 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) 内有一处块注释，将其删掉后再试一下？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 不是不是，我是说要解密的代码里面： 把注释和回车去掉，保证代码只有一行 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt;
>   
> 我有想做一个去除中间注释的，但是这玩意并不简单。所以现在只能手动去掉。
>  vm模块是虚拟机，但是实际上是有办法跳出虚拟机的。网上有一些比较安全的第三方虚拟机比如说vm2，只要重写virtualGlobalEval()函数，输入的是js字符串，return运行结果，然后保证每次执行用的同一个context就行了。
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

eval是极其不安全的，只要有心人往解密函数里面添加了恶意代码，就会对你的设备造成威胁，vm相对于eval比较安全，但仍然可以通过沙箱逃逸获取全局context。

**Comment by FoxNick** [comment]
我知道放虚拟机 更安全 只是 APP 需要 用JAVA的js引擎运行 NODE 不能支持&nbsp;
所以问了下你 你说改写virtualGlobalEval()函数 全局运行 我觉得 可以这样 就试了下
我是要把 node 的支持 改成 普通JS 能用的 放 js 引擎运行 不安全的 地方 尽量 在 java层 去 处理
以便能很好的运行 你这个解密工具




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月17日(星期四) 下午2:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14)





  
var globalEval = eval;&nbsp; &nbsp; &nbsp;//定义全局eval函数别名
 function virtualGlobalEval ( data ) {
 &nbsp; &nbsp; &nbsp; return globalEval(data);
 &nbsp; &nbsp; }
 
这样 就能解
 
------------------&nbsp;原始邮件&nbsp;------------------
 发件人:                                                                                                                        "NXY666/JsjiamiV6-Decryptor"                                                                                    @.&gt;;
 发送时间:&nbsp;2022年3月17日(星期四) 下午2:19
 @.&gt;;
 @.@.&gt;;
 主题:&nbsp;Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14)
 
可以解 这种情况 必须这么处理吗？如果不用 node 的VM 模块 普通JS 如何执行 解混淆函数
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年3月17日(星期四) 下午2:06 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) replaceObjFunc 这个里面的吗 ？好像不行 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年3月17日(星期四) 中午1:59 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) 内有一处块注释，将其删掉后再试一下？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 不是不是，我是说要解密的代码里面： 把注释和回车去掉，保证代码只有一行 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt;
 
我有想做一个去除中间注释的，但是这玩意并不简单。所以现在只能手动去掉。
 vm模块是虚拟机，但是实际上是有办法跳出虚拟机的。网上有一些比较安全的第三方虚拟机比如说vm2，只要重写virtualGlobalEval()函数，输入的是js字符串，return运行结果，然后保证每次执行用的同一个context就行了。
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you authored the thread.Message ID: @.***&gt;
  
eval是极其不安全的，只要有心人往解密函数里面添加了恶意代码，就会对你的设备造成威胁，vm相对于eval比较安全，但仍然可以通过沙箱逃逸获取全局context。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NXY666** [comment]
> 我知道放虚拟机 更安全 只是 APP 需要 用JAVA的js引擎运行 NODE 不能支持&nbsp;
> 所以问了下你 你说改写virtualGlobalEval()函数 全局运行 我觉得 可以这样 就试了下
> 我是要把 node 的支持 改成 普通JS 能用的 放 js 引擎运行 不安全的 地方 尽量 在 java层 去 处理
> 以便能很好的运行 你这个解密工具
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人: ***@***.***&gt;; 
> 发送时间: 2022年3月17日(星期四) 下午2:55
> 收件人: ***@***.***&gt;; 
> 抄送: ***@***.***&gt;; ***@***.***&gt;; 
> 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14)
> 
> 
> 
> 
> 
>   
> var globalEval = eval;&nbsp; &nbsp; &nbsp;//定义全局eval函数别名
>  function virtualGlobalEval ( data ) {
>  &nbsp; &nbsp; &nbsp; return globalEval(data);
>  &nbsp; &nbsp; }
>  
> 这样 就能解
>  
> ------------------&nbsp;原始邮件&nbsp;------------------
>  发件人:                                                                                                                        "NXY666/JsjiamiV6-Decryptor"                                                                                    @.&gt;;
>  发送时间:&nbsp;2022年3月17日(星期四) 下午2:19
>  @.&gt;;
>  @.@.&gt;;
>  主题:&nbsp;Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14)
>  
> 可以解 这种情况 必须这么处理吗？如果不用 node 的VM 模块 普通JS 如何执行 解混淆函数
>  …
>  ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年3月17日(星期四) 下午2:06 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) replaceObjFunc 这个里面的吗 ？好像不行 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年3月17日(星期四) 中午1:59 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) 内有一处块注释，将其删掉后再试一下？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 不是不是，我是说要解密的代码里面： 把注释和回车去掉，保证代码只有一行 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt;
>  
> 我有想做一个去除中间注释的，但是这玩意并不简单。所以现在只能手动去掉。
>  vm模块是虚拟机，但是实际上是有办法跳出虚拟机的。网上有一些比较安全的第三方虚拟机比如说vm2，只要重写virtualGlobalEval()函数，输入的是js字符串，return运行结果，然后保证每次执行用的同一个context就行了。
>  
> —
>  Reply to this email directly, view it on GitHub, or unsubscribe.
>  Triage notifications on the go with GitHub Mobile for iOS or Android.
>  You are receiving this because you authored the thread.Message ID: @.***&gt;
>   
> eval是极其不安全的，只要有心人往解密函数里面添加了恶意代码，就会对你的设备造成威胁，vm相对于eval比较安全，但仍然可以通过沙箱逃逸获取全局context。
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

只要能保证安全，怎么弄都行啦XD

**Comment by FoxNick** [comment]
好的 谢谢 指导 你不说 我总以为 是必须VM 才能运行&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月17日(星期四) 下午3:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14)





  
我知道放虚拟机 更安全 只是 APP 需要 用JAVA的js引擎运行 NODE 不能支持&nbsp;
 所以问了下你 你说改写virtualGlobalEval()函数 全局运行 我觉得 可以这样 就试了下
 我是要把 node 的支持 改成 普通JS 能用的 放 js 引擎运行 不安全的 地方 尽量 在 java层 去 处理
 以便能很好的运行 你这个解密工具
 
------------------&nbsp;原始邮件&nbsp;------------------
 发件人: @.&gt;;
 发送时间: 2022年3月17日(星期四) 下午2:55
 收件人: @.&gt;;
 抄送: @.&gt;; @.&gt;;
 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14)
 
var globalEval = eval;&nbsp; &nbsp; &nbsp;//定义全局eval函数别名
 function virtualGlobalEval ( data ) {
 &nbsp; &nbsp; &nbsp; return globalEval(data);
 &nbsp; &nbsp; }
 
这样 就能解
 
------------------&nbsp;原始邮件&nbsp;------------------
 发件人:                                                                                                                        "NXY666/JsjiamiV6-Decryptor"                                                                                    @.&gt;;
 发送时间:&nbsp;2022年3月17日(星期四) 下午2:19
 @.&gt;;
 @.@.&gt;;
 主题:&nbsp;Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14)
 
可以解 这种情况 必须这么处理吗？如果不用 node 的VM 模块 普通JS 如何执行 解混淆函数
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年3月17日(星期四) 下午2:06 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) replaceObjFunc 这个里面的吗 ？好像不行 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年3月17日(星期四) 中午1:59 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) 内有一处块注释，将其删掉后再试一下？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 不是不是，我是说要解密的代码里面： 把注释和回车去掉，保证代码只有一行 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt;
 
我有想做一个去除中间注释的，但是这玩意并不简单。所以现在只能手动去掉。
 vm模块是虚拟机，但是实际上是有办法跳出虚拟机的。网上有一些比较安全的第三方虚拟机比如说vm2，只要重写virtualGlobalEval()函数，输入的是js字符串，return运行结果，然后保证每次执行用的同一个context就行了。
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you authored the thread.Message ID: @.***&gt;
 
eval是极其不安全的，只要有心人往解密函数里面添加了恶意代码，就会对你的设备造成威胁，vm相对于eval比较安全，但仍然可以通过沙箱逃逸获取全局context。
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you authored the thread.Message ID: @.***&gt;
  
只要能保证安全，怎么弄都行啦XD
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NXY666** [comment]
> https://jhpc.manduhu.com/duoduo/js/play.js

新版本已更新，现在无需去除注释就可以完成解密了。

**Comment by FoxNick** [comment]
ok我试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月17日(星期四) 中午1:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14)





 
内有一处块注释，将其删掉后再试一下？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FoxNick** [comment]
清除注释 我让群里 的 JS 高手看看 怎么搞 已经说明 发给他们了&nbsp;
有方法 我发你看看
有能代替 那个VM 脱离 NODE 就好了&nbsp;
不然得装环境 或放 服务器运行 太费事了 既然是JS 解 我觉得还是原汁原味 人性话一些
这只是我的 想法建议 感谢您的开源 确实帮到我们不少




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月17日(星期四) 下午2:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14)





  
可以解 这种情况 必须这么处理吗？如果不用 node 的VM 模块 普通JS 如何执行 解混淆函数
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年3月17日(星期四) 下午2:06 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) replaceObjFunc 这个里面的吗 ？好像不行 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年3月17日(星期四) 中午1:59 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [NXY666/JsjiamiV6-Decryptor] 无法解密 (Issue #14) 内有一处块注释，将其删掉后再试一下？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 不是不是，我是说要解密的代码里面： 把注释和回车去掉，保证代码只有一行 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt;
  
我有想做一个去除中间注释的，但是这玩意并不简单。所以现在只能手动去掉。
 vm模块是虚拟机，但是实际上是有办法跳出虚拟机的。网上有一些比较安全的第三方虚拟机比如说vm2，只要重写virtualGlobalEval()函数，输入的是js字符串，return运行结果，然后保证每次执行用的同一个context就行了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NXY666** [comment]
> 清除注释 我让群里 的 JS 高手看看 怎么搞 已经说明 发给他们了&nbsp;
> 有方法 我发你看看
> 有能代替 那个VM 脱离 NODE 就好了&nbsp;
> 不然得装环境 或放 服务器运行 太费事了 既然是JS 解 我觉得还是原汁原味 人性话一些
> 这只是我的 想法建议 感谢您的开源 确实帮到我们不少

嗯嗯，我一开始就是打算在node写，浏览器限制比较多，文件提取也麻烦。如果你打算在浏览器上使用可以自己改一改，浏览器是非常安全的，所以不需要考虑安全问题。
