### ISSUE TITLE
pause语句导致代码错误

### ISSUE THREAD

**Issue by PYUDNG** [NXY666/JsjiamiV6-Decryptor#15]
![pause_error_2](https://user-images.githubusercontent.com/63054558/160765294-a1c227a7-3f7e-40fe-98c6-3ead2d958e8d.jpg)
![pause_error_1](https://user-images.githubusercontent.com/63054558/160765283-f8dc5e73-2316-4de4-901a-0dca1f3f5eec.jpg)
如图一，配置好`config.json`以后执行`node DecryptV6.js`会报错
如图二，根据报错`at pause (/Users/Administrator/Downloads/Compressed/JsjiamiV6-Decryptor-master/DecryptV6.js:276:5)`，将代码中的对应`pause()`一行注释掉，再次执行`node DecryptV6.js`即可正常

注：
1. 所有文件均如此，并不是某个特定的代码/文件导致的问题。
2. 可以保证`config.json`中目标文件路径没有写错（对应着正确的文件路径），`config.json`只修改了目标路径字段。

**Comment by NXY666** [comment]
啊这，这是我第一次遇到pause出问题，我查一下这个错误是什么玩意。

**Comment by NXY666** [comment]
问题已找到，这个函数似乎不兼容linux，近期会尝试进行修复。
在此期间你可以尝试把pause函数内的`fs.readSync(0, Buffer.alloc(1), 0, 1, null);`注释掉然后运行，这样就不会报错，就是无法达到暂停的效果了。

**Comment by NXY666** [comment]
nodejs在linux下似乎无法使用控制台与用户交互。
新版本中新增了`安静模式`，可在配置文件中启用它选择以跳过暂停来“解决”报错的问题。
![image](https://user-images.githubusercontent.com/62371554/161397182-886a24cd-2fa3-4c02-ae5b-fdc6e71db8eb.png)
