### ISSUE TITLE
卡在 ”正在解除代码块加密……“ 代码里有U+202E和U+202B

### ISSUE THREAD

**Issue by ceom123** [NXY666/JsjiamiV6-Decryptor#2]
检查过版本是jsjiami.com.v6
我试过直接替换掉这两个符号 但是解密出错，不替换的话 会卡死在 ”正在解除代码块加密……“
图片在这里(###)

**Comment by NXY666** [comment]
可以把脚本发上来吗（存github上也行），我检查一下，因为理论上那个“标记”选项是不会影响解密的。

**Comment by ceom123** [comment]
> 可以把脚本发上来吗（存github上也行），我检查一下，因为理论上那个“标记”选项是不会影响解密的。

不好意思，解决了  卡了十分钟后解密成功了。。。。 不知道为什么会突然卡住 脚本1MB大小

**Comment by ceom123** [comment]
谢谢

**Comment by NXY666** [comment]
哈哈，1MB太大了，代码块解密本身比较费时间，我那块效率做的也不是很好。
