### ISSUE TITLE
看下这种 不能解密

### ISSUE THREAD

**Issue by FoxNick** [NXY666/JsjiamiV6-Decryptor#21]
https://sf3-cdn-tos.douyinstatic.com/obj/tos-cn-i-xg/1c1235896bfc477bbc760768ab2ff5f5?.play.min.js?t=1652182107

**Comment by NXY666** [comment]
这看起来是一个典型的经过jsjiamiV6加密的js——
理论上解密器应该是要支持的，但是现在看来会报错，，，

**Comment by NXY666** [comment]
问题已经找到了，我现在尝试进行修复。
