### ISSUE TITLE
建议模块化封装，改写方法

### ISSUE THREAD

**Issue by wingeva1986** [NXY666/JsjiamiV6-Decryptor#24]
我架了web服务，集成了你的v6还有其他如ast解混淆的方法，发现一通过module引入v6就导致其他的解混淆方法报错，大概率是Array.prototype之类的全局变量污染导致的，还有解混淆调用各种函数的过程也建议抽出来集中在一起。所以，建议改写下方法，方便集成调用。

**Comment by NXY666** [comment]
你说的有道理...
其实我之前是有想过将脚本模块化的。但是遇到了很多问题，后来就不了了之了。
比如说我一开始是想做成互动式脚本，就是途中会有提示之类的，这就意味着模块化之后局限性非常大，因为不经修改的话它很难实现自动化执行。
还有一个是它现在流程几乎是在第一层完成的，如果要模块化按我的想法我可能要在外面套一层函数。u1s1，我很难接受...

你对此有什么更多的建议吗😞

**Comment by wingeva1986** [comment]
> 你说的有道理... 其实我之前是有想过将脚本模块化的。但是遇到了很多问题，后来就不了了之了。 比如说我一开始是想做成互动式脚本，就是途中会有提示之类的，这就意味着模块化之后局限性非常大，因为不经修改的话它很难实现自动化执行。 还有一个是它现在流程几乎是在第一层完成的，如果要模块化按我的想法我可能要在外面套一层函数。u1s1，我很难接受...
> 
> 你对此有什么更多的建议吗😞

https://github.com/Tsaiboss/decodeObfuscator
这个是解ob的

看看有没值得参考的地方:)

**Comment by NXY666** [comment]
我一开始做的时候是想弄一个用nodejs实现的、无依赖、控制台互动式的项目，所以做网页的话不太现实。
但是如果和解ob的那个项目一样，那其实我就改一个prototype的函数名称就行了吧？启动了安静模式就不会有互动。
但是这个解密器在很多情况下会有局限性，比如说有时候并不能一次性解密完全，可能需要调配置并对结果文件多次解密才能完全解密，你确定要集成进去吗？

**Comment by wingeva1986** [comment]
ast我也适配了v6 v5的解法，只是想互补而已。然后刚才我排查了一下问题，确定是Array.prototype.top引起的，我改掉后就不报错了。

**Comment by NXY666** [comment]
啊哈，那——就没我啥事了吧？
