### ISSUE TITLE
一个比较大的文件解密卡在解除代码块加密

### ISSUE THREAD

**Issue by huanzhiyi** [NXY666/JsjiamiV6-Decryptor#27]
https://raw.githubusercontent.com/Cuiyim/Jtai_2022/34e7170cfa8f4891474108466f397ecb0bf96dac/maccms10/dmbofangqi1.7/js/Maoplay.js

请问是什么问题

**Comment by NXY666** [comment]
理论上不是卡住了，只是有点慢，emm

**Comment by huanzhiyi** [comment]
> 理论上不是卡住了，只是有点慢，emm
> 你大概等了多久？

十几分钟还是百分之0😂

**Comment by NXY666** [comment]
呃，我看了一下，这JS是有亿点点长。emm但是我过两周要期末考了，还有一堆课设要折腾。等我考完了给你看下吧qwq

**Comment by huanzhiyi** [comment]
> 呃，我看了一下，这JS是有亿点点长。emm但是我过两周要期末考了，还有一堆课设要折腾。等我考完了给你看下吧qwq

好的 感谢 祝你考个好成绩👍

**Comment by NXY666** [comment]
![image](https://user-images.githubusercontent.com/62371554/176125953-596b1397-b966-4398-b91b-9156a2e8eff9.png)
可能真的是太长了吧，我等了几分钟就好了😂。
理论上这个js的最外层有两个语句，然后第一个语句几乎是整个js的全部。
刚好进度条是按照最外层分配进度的（如果是两条语句就一条50%），所以等半天还是0%是因为第一条语句真的需要花很长时间解密😂

**Comment by huanzhiyi** [comment]
> 理论上这个js的最外层有两个语句，然后第一个语句几乎是整个js的全部

好的，感谢 这个文件实在太大了

**Comment by NXY666** [comment]
但是看起来整体解密效果并不理想，我还会再改进的😣

**Comment by NXY666** [comment]
噢今天下午是我不小心把它改坏了所以才那么快且效果那么差。
今晚我又跑了一遍，花了半个多小时，能差不多都解密完。主要是前面有一个非常大的代码块，，，
![image](https://user-images.githubusercontent.com/62371554/176192091-265a786b-87ab-4eb7-92a6-54e55294c3b2.png)

**Comment by huanzhiyi** [comment]
> 噢今天下午是我不小心把它改坏了所以才那么快且效果那么差。 今晚我又跑了一遍，花了半个多小时，能差不多都解密完。主要是前面有一个非常大的代码块，，， ![image](https://user-images.githubusercontent.com/62371554/176192091-265a786b-87ab-4eb7-92a6-54e55294c3b2.png)

难怪那天尝试 感觉卡住了
