### ISSUE TITLE
出现下图问题，是node版本问题？

### ISSUE THREAD

**Issue by gitupdate** [NXY666/JsjiamiV6-Decryptor#28]
node版本：v16.4.2

![image](https://user-images.githubusercontent.com/92412374/171643677-ab054900-222d-4719-b638-50051f3bba80.png)

**Comment by NXY666** [comment]
啊，你这是什么系统呀，怎么会没这个方法...

**Comment by gitupdate** [comment]
> 啊，你这是什么系统呀，怎么会没这个方法...

window系统，  window 10 ，之前好好的， 昨晚解密一个js ,突然提示这个错误

**Comment by NXY666** [comment]
我node版本是v16.14.0，版本是差不多的，你这错误我没遇到过，过几周我考完试我试试加个catch拦一下...

**Comment by chanho0** [comment]
v16.15.0同错误

**Comment by NXY666** [comment]
> v16.15.0同错误

我查了一下，这个函数好像是被废除了，我到时候删了这玩意。

**Comment by gitupdate** [comment]
> > v16.15.0同错误
> 
> 我查了一下，这个函数好像是被废除了，我到时候删了这玩意。

好的，  那应该就是要手动 按任意键了

**Comment by NXY666** [comment]
新版本尝试避开了这个问题，若发现没有那个方法会改为提示“请按回车键继续”。但是因为我这里没有出现这个情况，所以还需要你测试一下。
