### ISSUE TITLE
这两个js文件解不了

### ISSUE THREAD

**Issue by wingeva1986** [NXY666/JsjiamiV6-Decryptor#3]
https://qwezxcedc1.gitee.io/player/js/play.js

https://player.kongbuya.com/js/play.js

麻烦看一下能否改进

**Comment by NXY666** [comment]
它们有点复杂，如果要找错可能要花比较长的时间。但是这几天在做项目比较没时间，我年后帮你看看。

**Comment by Manx98** [comment]
这个是去除部分混淆的结果，由于是程序自动处理得到，无法保证正确性，如有错误可以欢迎指出 https://github.com/Manx98/Test/

**Comment by wingeva1986** [comment]
> 这个是去除部分混淆的结果，由于是程序自动处理得到，无法保证正确性，如有错误可以欢迎指出 https://github.com/Manx98/Test/

这个结果也是用这个项目的程序跑出来的吗

**Comment by NXY666** [comment]
> > 这个是去除部分混淆的结果，由于是程序自动处理得到，无法保证正确性，如有错误可以欢迎指出 https://github.com/Manx98/Test/
> 
> 这个结果也是用这个项目的程序跑出来的吗

我今天下午试的时候发现了一些问题，但是修改完之后仍有报错，年后我会进行一波更新。

**Comment by Manx98** [comment]
不是，是我自己写的程序

**Comment by Manx98** [comment]
> > > 这个是去除部分混淆的结果，由于是程序自动处理得到，无法保证正确性，如有错误可以欢迎指出 https://github.com/Manx98/Test/
> > 
> > 
> > 这个结果也是用这个项目的程序跑出来的吗
> 
> 我今天下午试的时候发现了一些问题，但是修改完之后仍有报错，年后我会进行一波更新。

不是，这是我自己写的程序跑出来的结果。

**Comment by Manx98** [comment]
> > > 这个是去除部分混淆的结果，由于是程序自动处理得到，无法保证正确性，如有错误可以欢迎指出 https://github.com/Manx98/Test/
> > 
> > 
> > 这个结果也是用这个项目的程序跑出来的吗
> 
> 我今天下午试的时候发现了一些问题，但是修改完之后仍有报错，年后我会进行一波更新。

直接操作AST来去除混淆的方式要更好一些，只不过实现起来会比较繁琐

**Comment by NXY666** [comment]
https://qwezxcedc1.gitee.io/player/js/play.js
我尝试解密它的时候发现这个js存在switch死代码和加密对象嵌套的情况，需要进行多次解密，这是我之前从未遇到的，可能得花一段时间去思考。
但是经过一晚上的修改，已经能在第一遍相对正确地进行解密了。
我已经完成了推送，还请试一下新版本哦~

**Comment by NXY666** [comment]
已经针对Oo0模式的加密进行更新，可以尝试用新版本解密。

**Comment by wingeva1986** [comment]
> 已经针对Oo0模式的加密进行更新，可以尝试用新版本解密。

https://player.kongbuya.com/js/play.js
这个提示解密器识别失败了

**Comment by wingeva1986** [comment]
> > 已经针对Oo0模式的加密进行更新，可以尝试用新版本解密。
> 
> https://player.kongbuya.com/js/play.js 这个提示解密器识别失败了

奇怪了，这个文件post过去，代码字符串会逆序

**Comment by NXY666** [comment]
> > > 已经针对Oo0模式的加密进行更新，可以尝试用新版本解密。
> > 
> > https://player.kongbuya.com/js/play.js 这个提示解密器识别失败了
> 
> 奇怪了，这个文件post过去，代码字符串会逆序

逆序是因为他加入了某些特殊字符，你可以把编辑器的编码调成ASCII，然后那些字符就失效了。

**Comment by wingeva1986** [comment]
> > > > 已经针对Oo0模式的加密进行更新，可以尝试用新版本解密。
> > > 
> > > 
> > > https://player.kongbuya.com/js/play.js 这个提示解密器识别失败了
> > 
> > 
> > 奇怪了，这个文件post过去，代码字符串会逆序
> 
> 逆序是因为他加入了某些特殊字符，你可以把编辑器的编码调成ASCII，然后那些字符就失效了。

对这个文件需要预处理吗，现在我用最新版本地跑这个文件，是会提示解密识别失败。

`* 正在解除全局加密……
【警告】解密器识别失败，可在GitHub上提交issue以寻找原因。
[请按任意键继续]
evalmachine.<anonymous>:1
('00'+_0xac473['charCodeAt'](_0x3f1d67)


SyntaxError: Unexpected end of input
[90m    at new Script (vm.js:99:7)[39m
[90m    at createScript (vm.js:249:10)[39m
[90m    at Object.runInContext (vm.js:280:10)[39m
    at virtualGlobalEval (C:\Users\Administrator\Desktop\python\JsjiamiV6-Dec
tor-master\decryptv6.js:332:12)
    at virtualEval (C:\Users\Administrator\Desktop\python\JsjiamiV6-Decryptor
ster\decryptv6.js:329:9)
    at C:\Users\Administrator\Desktop\python\JsjiamiV6-Decryptor-master\decry
6.js:516:75
    at Array.map (<anonymous>)
    at decryptGlobalJs (C:\Users\Administrator\Desktop\python\JsjiamiV6-Decry
r-master\decryptv6.js:510:5)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\python\JsjiamiV6-De
ptor-master\decryptv6.js:523:19)
[90m    at Module._compile (internal/modules/cjs/loader.js:1147:30)[39m
`

**Comment by wingeva1986** [comment]
这个js文件里有一堆Unicode字符，包括一些变量名

**Comment by NXY666** [comment]
> > 已经针对Oo0模式的加密进行更新，可以尝试用新版本解密。
> 
> https://player.kongbuya.com/js/play.js 这个提示解密器识别失败了

是这样的，我看源文件前有一段注释，你把注释删掉试试，解密器没有检测注释，所以有注释的话会被误判。
但是呢这个js好像是开了自卫模式，并没有解密的很干净，这个我之后还会继续优化。

**Comment by NXY666** [comment]
> 这个js文件里有一堆Unicode字符，包括一些变量名和常见的函数名，比如上面报错那句CharCodeAt的第二个C和A字符

是这样的，加密器有一个选项是“标记”，开启后会在很多地方插入反转字符之类的东西。
这个对解密过程是没有影响的，但是对阅读有影响。

**Comment by wingeva1986** [comment]
> > > 已经针对Oo0模式的加密进行更新，可以尝试用新版本解密。
> > 
> > 
> > https://player.kongbuya.com/js/play.js 这个提示解密器识别失败了
> 
> 是这样的，我看源文件前有一段注释，你把注释删掉试试，解密器没有检测注释，所以有注释的话会被误判。 还有我看var前面有个空格，那个也去掉，我怕识别的时候有那个空格正则匹配不到。 但是呢这个js好像是开了自卫模式，并没有解密的很干净，这个我之后还会继续优化。

注释删了是一样的报错，可能是开了自卫模式吧

**Comment by NXY666** [comment]
> > > > 已经针对Oo0模式的加密进行更新，可以尝试用新版本解密。
> > > 
> > > 
> > > https://player.kongbuya.com/js/play.js 这个提示解密器识别失败了
> > 
> > 
> > 是这样的，我看源文件前有一段注释，你把注释删掉试试，解密器没有检测注释，所以有注释的话会被误判。 还有我看var前面有个空格，那个也去掉，我怕识别的时候有那个空格正则匹配不到。 但是呢这个js好像是开了自卫模式，并没有解密的很干净，这个我之后还会继续优化。
> 
> 注释删了是一样的报错，可能是开了自卫模式吧

我删除注释后成功运行了：
![image](https://user-images.githubusercontent.com/62371554/154441613-56f3740b-6214-4fca-9a17-427dd0ea8333.png)
![image](https://user-images.githubusercontent.com/62371554/154441673-95e2ea29-4a66-4c38-9988-81278fbea4bf.png)

**Comment by wingeva1986** [comment]
> > > > > 已经针对Oo0模式的加密进行更新，可以尝试用新版本解密。
> > > > 
> > > > 
> > > > https://player.kongbuya.com/js/play.js 这个提示解密器识别失败了
> > > 
> > > 
> > > 是这样的，我看源文件前有一段注释，你把注释删掉试试，解密器没有检测注释，所以有注释的话会被误判。 还有我看var前面有个空格，那个也去掉，我怕识别的时候有那个空格正则匹配不到。 但是呢这个js好像是开了自卫模式，并没有解密的很干净，这个我之后还会继续优化。
> > 
> > 
> > 注释删了是一样的报错，可能是开了自卫模式吧
> 
> 我删除注释后成功运行了： ![image](https://user-images.githubusercontent.com/62371554/154441613-56f3740b-6214-4fca-9a17-427dd0ea8333.png) ![image](https://user-images.githubusercontent.com/62371554/154441673-95e2ea29-4a66-4c38-9988-81278fbea4bf.png)

呃，var 前面也有个字符要删掉，可以了，感谢~

**Comment by NXY666** [comment]
> https://qwezxcedc1.gitee.io/player/js/play.js 我尝试解密它的时候发现这个js存在switch死代码和加密对象嵌套的情况，需要进行多次解密，这是我之前从未遇到的，可能得花一段时间去思考。 但是经过一晚上的修改，已经能在第一遍相对正确地进行解密了。 我已经完成了推送，还请试一下新版本哦~

新版本已支持重复解密。一次解密完成后若发现有未清理干净的内容，可将DecryptResult3.js的回车删除，然后把FILE_NAME设置为DecryptResult3.js（结果4进行了内容格式化，原结构已被破坏，无法用于解密），然后重新运行即可（多次运行是没有全局加密函数的，所以会触发警告，忽略即可）。
