### ISSUE TITLE
不能解除代码块和全局，麻烦看看

### ISSUE THREAD

**Issue by goodwenhao** [NXY666/JsjiamiV6-Decryptor#30]
js地址
https://github.com/goodwenhao/study/blob/main/test.js

**Comment by NXY666** [comment]
我大概30号能忙完，到时候我会看看的。

**Comment by goodwenhao** [comment]
好的，辛苦啦

**Comment by NXY666** [comment]
这个JS我看了一下，全局和代码块是可以解密的，主要的问题是使用了类，但是我没有特别去支持类的解密，在新版本中我进行了一点点的修复，现在解密这个js不会有很大的问题了。

**Comment by goodwenhao** [comment]
![image](https://user-images.githubusercontent.com/106424301/176361095-99ca99af-9558-4a52-b088-4b45d200a613.png)
大佬，我更新了，还是解不开呢

**Comment by NXY666** [comment]
这个函数我看了，它好像指向的是js最顶部的一个函数（中转了几次），但是它似乎不属于v6的加密，可能是作者自己写的。

**Comment by goodwenhao** [comment]
> 这个函数我看了，它好像指向的是js最顶部的一个函数（中转了几次），但是它似乎不属于v6的加密，可能是作者自己写的。

好吧。手搓了。谢谢。
