### ISSUE TITLE
全局加密识别失败

### ISSUE THREAD

**Issue by Colorsssss** [NXY666/JsjiamiV6-Decryptor#36]
`https://github.com/smiek2121/scripts/blob/master/gua_opencard195.js`
* 解除全局加密 [ ==========                                       ]
【警告】解密函数识别失败，

**Comment by NXY666** [comment]
这个JS的第67行才是加密内容，你需要将它单独提取出来才能进行解密。

**Comment by Colorsssss** [comment]
好的！成功了 
我以为要运行起来才能解密
