### ISSUE TITLE
可以考虑一下使用ast来解析

### ISSUE THREAD

**Issue by coder-gao** [NXY666/JsjiamiV6-Decryptor#38]
### 建议详情

可以考虑一下使用ast来解析，

**Comment by NXY666** [comment]
其实我一开始就有考虑要用正则还是ast，最终是想说试试可不可能只用正则解析JS然后完成解密。
主要还是想锻炼自己的JS技术（所以代码里面完全没引用已经造好的轮子，vm2是实在做不到所以才用的别人的），我本身也没有什么解密JS的需求，纯粹就是为了练习。
