### ISSUE TITLE
大佬，变量混淆一下，貌似就无法识别了，用idea跑的

### ISSUE THREAD

**Issue by zyzzmd** [NXY666/JsjiamiV6-Decryptor#4]
[样本](https://wwn.lanzoul.com/iEBe80014b1i) #

**Comment by NXY666** [comment]
OＯ0$混淆的问题前几天已经发现了，是用replace的时候被$干扰到了。但是我最近比较忙，没时间弄，过几天我会找个时间改一下的。

**Comment by zyzzmd** [comment]
好的，感谢😊

**Comment by zyzzmd** [comment]
好的，感谢😊

#

**Comment by zyzzmd** [comment]
好的，感谢😊

**Comment by NXY666** [comment]
我已经针对这个js进行了更新，稍微检查了一下效果还不错。

**Comment by zyzzmd** [comment]
好的👍👍
