### ISSUE TITLE
尝试关闭不存在的“()”

### ISSUE THREAD

**Issue by Awuqing** [NXY666/JsjiamiV6-Decryptor#40]
### 操作系统

Windows

### 问题详情

执行解密时提示
throw "ParseError: 尝试关闭不存在的“()”。";
^
ParseError: 尝试关闭不存在的“()”。
(Use node --trace-uncaught ... to show where the exception was thrown)

### 目标代码

```JavaScript
https://idea.ainidc.com/Header.js
```

**Comment by NXY666** [comment]
问题原因已找到，我会尽快找时间修复的。

**Comment by NXY666** [comment]
这个问题的解决难度较大，可能会花费较长的时间来修复这个问题。

**Comment by NXY666** [comment]
问题已尝试修复，可以用最新版本试试解密。
