### ISSUE TITLE
对于二次jsjiami加密的解密

### ISSUE THREAD

**Issue by TongLin138** [NXY666/JsjiamiV6-Decryptor#48]
## 功能建议

[举例文件](https://raw.githubusercontent.com/KingRan/KR/main/function/krgetToken.js)

上面链接中js文件采用了两步骤进行加密
先使用v6加密，再使用 https://www.sojson.com/javascriptobfuscator.html  中JS加密（高级）的加密方式。
请问作者可否对该类加密进行支持。

**Comment by NXY666** [comment]
啊这，如果设计别的加密就很难办了，因为我只研究过v6的加密，别的加密还得重新弄一个...

**Comment by TongLin138** [comment]
嗯，好的，感谢回复。
