### ISSUE TITLE
可以支持对jsjiami.v5的支持吗？

### ISSUE THREAD

**Issue by buaaflyaway** [NXY666/JsjiamiV6-Decryptor#49]
### 建议详情

可以加入对jsjiami.v5的支持吗？

**Comment by NXY666** [comment]
呃，现在主要是我很难见到v5的加密。而且我可能没有更多的精力去同时维护两个解密器，况且现在v6的解密器还有很多细节问题（比如不兼容一些不常见的语法）没有解决，暂时没有支持其他版本解密的打算😂
