### ISSUE TITLE
这个js解密不完全

### ISSUE THREAD

**Issue by wingeva1986** [NXY666/JsjiamiV6-Decryptor#5]
https://player.suoyou.live/js/play.js

**Comment by NXY666** [comment]
目前我只做了autojs模式下的加密项解密，其他模式的话我比较不熟悉，之后我会尝试兼容的。
这个好像和https://player.kongbuya.com/js/play.js感觉是同一个东西？只是加密的方式不一样。

**Comment by wingeva1986** [comment]
> 目前我只做了autojs模式下的加密项解密，其他模式的话我比较不熟悉，之后我会尝试兼容的。 这个好像和[https://player.kongbuya.com/js/play.js感觉是同一个东西？只是加密的方式不一样。](https://player.kongbuya.com/js/play.js%E6%84%9F%E8%A7%89%E6%98%AF%E5%90%8C%E4%B8%80%E4%B8%AA%E4%B8%9C%E8%A5%BF%EF%BC%9F%E5%8F%AA%E6%98%AF%E5%8A%A0%E5%AF%86%E7%9A%84%E6%96%B9%E5%BC%8F%E4%B8%8D%E4%B8%80%E6%A0%B7%E3%80%82)

类似的代码结构
