### ISSUE TITLE
2.9.1版本解密应该是有问题

### ISSUE THREAD

**Issue by huanzhiyi** [NXY666/JsjiamiV6-Decryptor#51]
### 操作系统

Windows

### Node.js 版本号

v16.14.0

### 问题详情

上一个版本解密出来 代码有两千多行，新的版本解密出来只有一千多行。代码应该是缺少了，新版本解密文件后，代码替换加密文件后就用不了。上一个版本解密出来，能用但是还有点问题，替换加密问题有点小bug，所以尝试用新版本测试

### 目标代码

```JavaScript
https://t.wss.ink/f/96ar5ynf0od
```

**Comment by NXY666** [comment]
问题已经找到了，因为新版本改了一些比较重要的函数，现在它可能还不是很好使，我会尽快弄好
对了，替换加密有什么问题吗，可以也提出来瞧瞧。

**Comment by huanzhiyi** [comment]
> 问题已经找到了，因为新版本改了一些比较重要的函数，现在它可能还不是很好使，我会尽快弄好 对了，替换加密有什么问题吗，可以也提出来瞧瞧。

这是一个播放器代码，替换文件后，直接是黑屏

**Comment by NXY666** [comment]
> > 问题已经找到了，因为新版本改了一些比较重要的函数，现在它可能还不是很好使，我会尽快弄好 对了，替换加密有什么问题吗，可以也提出来瞧瞧。
> 
> 这是一个播放器代码，替换文件后，直接是黑屏

😂其实我这测试里面是有这个js的，但是那天偷懒没跑测试，就尴尬了

**Comment by huanzhiyi** [comment]
> > > 问题已经找到了，因为新版本改了一些比较重要的函数，现在它可能还不是很好使，我会尽快弄好 对了，替换加密有什么问题吗，可以也提出来瞧瞧。
> > 
> > 
> > 这是一个播放器代码，替换文件后，直接是黑屏
> 
> 😂其实我这测试里面是有这个js的，但是那天偷懒没跑测试，就尴尬了

嗯，上一个版本替换后就是不能正常时移 所以尝试新的版本，发现直接黑屏。对比了一下，上一个版本解密和这个版本解密的代码发现，这个版本代码少了不少行代码

**Comment by NXY666** [comment]
我已推送了新版本，你可以试一下有没有恢复正常。
如果还是有问题的话可不可以给个测试demo我自己跑一下这个js
它结构太复杂了，如果要一行一行看效率太低。

**Comment by huanzhiyi** [comment]
> 我已推送了新版本，你可以试一下有没有恢复正常。 如果还是有问题的话可不可以给个测试demo我自己跑一下这个js 它结构太复杂了，如果要一行一行看效率太低。

好的 感谢

**Comment by huanzhiyi** [comment]
> 我已推送了新版本，你可以试一下有没有恢复正常。 如果还是有问题的话可不可以给个测试demo我自己跑一下这个js 它结构太复杂了，如果要一行一行看效率太低。

https://t.wss.ink/f/96fzuln7nzh 这个是整个播放器文件，不过需要php环境使用 js加密文件在里面。测试了解密后的文件和 2.9.0一样效果 时间进度显示不正确不能正常时移 不知道是不是js里面加了什么验证文件的。

**Comment by huanzhiyi** [comment]
> 我已推送了新版本，你可以试一下有没有恢复正常。 如果还是有问题的话可不可以给个测试demo我自己跑一下这个js 它结构太复杂了，如果要一行一行看效率太低。

另外maoplay.js那个文件应该是 https://raw.githubusercontent.com/cairs00/yzmplayer/main/player/js/yzmplayer.js 修改后加密的 或者可以参考一下

**Comment by huanzhiyi** [comment]
> > https://t.wss.ink/f/96fzuln7nzh 这个是整个播放器文件，不过需要php环境使用 js加密文件在里面。测试了解密后的文件和 2.9.0一样效果 时间进度显示不正确不能正常时移 不知道是不是js里面加了什么验证文件的。
> 
> 啊这，你有没有试过不用result6，用前面几个解密结果能正常使用吗

这倒是没有用过 可以一试 之前一直都是用result6

**Comment by NXY666** [comment]
> 这倒是没有用过 可以一试 之前一直都是用result6

主要是这玩意实在是太大了，我没精力去一点一点去看emm，如果你能自己找到问题所在是最好，不行的话我也没有很好的办法😣

**Comment by huanzhiyi** [comment]
> > 这倒是没有用过 可以一试 之前一直都是用result6
> 
> 主要是这玩意实在是太大了，我没精力去一点一点去看emm，如果你能自己找到问题所在是最好，不行的话我也没有很好的办法😣

的确太大，主要是不太懂js 如果暂时解决不了 就先放放吧 或者以后有方法解决

**Comment by huanzhiyi** [comment]
> > 这倒是没有用过 可以一试 之前一直都是用result6
> 
> 主要是这玩意实在是太大了，我没精力去一点一点去看emm，如果你能自己找到问题所在是最好，不行的话我也没有很好的办法😣

另外，测试过 只有result1是正常的 其余情况一样

**Comment by NXY666** [comment]
> https://t.wss.ink/f/96fzuln7nzh 这个是整个播放器文件，不过需要php环境使用 js加密文件在里面。测试了解密后的文件和 2.9.0一样效果 时间进度显示不正确不能正常时移 不知道是不是js里面加了什么验证文件的。

这样，你开一个新issue，讲2.9.0的那个问题。我对比了半天好像是看到了一点问题（但是不知道是不是因为这个）。到时候我改好了在新issue那里跟你说，你再试试看。

**Comment by huanzhiyi** [comment]
> 我对比了半天好像是看到了一点问题

好的 辛苦了 感谢 这就开一个
