### ISSUE TITLE
解密后，替换文件出现问题

### ISSUE THREAD

**Issue by huanzhiyi** [NXY666/JsjiamiV6-Decryptor#52]
### 操作系统

Windows

### Node.js 版本号

v16.14.0

### 问题详情

文件解密后，替换文件出现bug。尝试解密的文件，发现只有result1文件替换后功能正常。

### 目标代码

```JavaScript
https://github.com/NXY666/JsjiamiV6-Decryptor/issues/51
```

**Comment by NXY666** [comment]
最近开学了，还要做项目，可能得过一段时间才有时间弄。

**Comment by huanzhiyi** [comment]
> 最近开学了，还要做项目，可能得过一段时间才有时间弄。

嗯 先忙主要的 研究这东西急不了 反馈这问题是主要想项目更完善 目前解密效果还是不错的  所以不用急于一时

**Comment by NXY666** [comment]
`2.10.0`已更新，已尝试解决该问题。

**Comment by huanzhiyi** [comment]
> `2.10.0`已更新，已尝试解决该问题。

中秋节快乐，有时间再去测试一下 感谢
