### ISSUE TITLE
解密器识别失败

### ISSUE THREAD

**Issue by double-jin2007** [NXY666/JsjiamiV6-Decryptor#53]
### 操作系统

Windows

### 问题详情

【警告】解密器识别失败

### 目标代码

```JavaScript
http://170.85tt.cn/seos_v3.js
```

**Comment by double-jin2007** [comment]
node版本：v14.17.5

**Comment by NXY666** [comment]
![image](https://user-images.githubusercontent.com/62371554/188435909-a568386e-a1a1-4b47-b281-0a65fd86e805.png)
识别是正常的呀😶

**Comment by double-jin2007** [comment]
不用了&nbsp; 可以了 谢谢

**Comment by double-jin2007** [comment]
哪里不对了吗？总是失败&nbsp;能否解密的给一份

**Comment by NXY666** [comment]
> 哪里不对了吗？总是失败&nbsp;能否解密的给一份

你是直接下载JS还是复制后粘贴？
