### ISSUE TITLE
解密函数识别失败

### ISSUE THREAD

**Issue by FatMii** [NXY666/JsjiamiV6-Decryptor#54]
### 操作系统

Windows

### Node.js 版本号

16.17.0

### 问题详情

解密函数识别失败，如下图所示：
![image](https://user-images.githubusercontent.com/39074672/188601713-a6f9fc4b-4947-4678-bfb4-9e20b46cc089.png)

### 目标代码

```JavaScript
<script src="https://gist.github.com/FatMii/ef018a997d6f53df36593e67178ad971.js"></script>
```

**Comment by NXY666** [comment]
这个js应该是被人为地修改过了，字符串全部使用双引号。如果只是使用jsjiami加过的js，所有字符串都应该使用“'”而不是“"”，因此我只适配了单引号……

**Comment by FatMii** [comment]
> 这个js应该是被人为地修改过了，字符串全部使用双引号。如果只是使用jsjiami加过的js，所有字符串都应该使用“'”而不是“"”，因此我只适配了单引号……

是的，被我格式化过了，我拿未格式化的代码尝试了，没报错。谢谢！

**Comment by NXY666** [comment]
🤣
