### ISSUE TITLE
运算优先级问题，详情请看图及代码

### ISSUE THREAD

**Issue by bangenlanbai** [NXY666/JsjiamiV6-Decryptor#55]
### 操作系统

Windows

### Node.js 版本号

v16.15.0

## 加密代码片段
![image](https://user-images.githubusercontent.com/54814510/188889333-fcebaa27-e658-4b32-b3b9-f4b9756efdb1.png)

## 还原代码片段
![image](https://user-images.githubusercontent.com/54814510/188890458-4f49d566-38a3-4de8-8c26-ddba659c52ae.png)

### 目标代码

```JavaScript
https://github.com/bangenlanbai/JsjiamiV6-Decryptor/blob/master/Issue/target.js
```

**Comment by NXY666** [comment]
是的，我已经发现了，这是自始至终都存在的问题，已经正在尝试修复。
但是它太难了，我折腾了好几天都没整出来...可能还需要一些时间。

**Comment by bangenlanbai** [comment]
> 是的，我已经发现了，这是自始至终都存在的问题，已经正在尝试修复。 但是它太难了，我折腾了好几天都没整出来...可能还需要一些时间。

问题不大，只是今天发现了这个问题。目前来说项目已经很完善了，至少对于我来说是这样的，感谢分享！

**Comment by NXY666** [comment]
有这个js未格式化过的源文件吗，那个格式化后的我好像执行不了。

**Comment by bangenlanbai** [comment]
源文件已更新
https://github.com/bangenlanbai/JsjiamiV6-Decryptor/blob/master/Issue/target.js

**Comment by NXY666** [comment]
`2.10.0`已更新，已尝试解决该问题。

**Comment by bangenlanbai** [comment]
很棒! 完美! 刚刚实现用正则替换 你这边就处理好了.
