### ISSUE TITLE
请问这种是不是不能直接解的

### ISSUE THREAD

**Issue by huanzhiyi** [NXY666/JsjiamiV6-Decryptor#7]
var _0xodS='jsjiami.com.v6',_0xodS_=['‮_0xodS'],_0x537b=[_0xodS,'wqbCncKrJMONwrt+','w5BGIMKH','W2VT','LFfDmsKswq7CvsKF','DsKTwrs3KB1Iwrk=','w4nCo0Y=','EGjDi8O9','fMOvQsKDPw==','PzvDjsO4woY=','wqMyGMO1MQ==','JBNtw67CpcOo','bcKfEMO5Ag==','QFUVworDpQ==','w4jCi3hywo4d','VMKvwqpQIBc=','d1vCiw==','PsOtMk0=','w4XDkCAVwqQ=','w6hlIQ==','wqpfw7jDug==','MA5Ew6jChg==','HcOVJA==','dw/ClcKA','w41INsKRwq4=','BFnDvg==','jfsbjKiJRKaQmxiLqN.lfhcoqm.v6HQ=='];if(function(_0x5069e6,_0x26a517,_0x179b9c){function _0x4440eb(_0x2fc53c,_0x47d939,_0x494690,_0x4cae9a,_0x28093b,_0x6830c){_0x47d939=_0x47d939>>0x8,_0x28093b='po';var _0x5e04f9='shift',_0x4e1e23='push',_0x6830c='‮';if(_0x47d939<_0x2fc53c){while(--_0x2fc53c){_0x4cae9a=_0x5069e6[_0x5e04f9]();if(_0x47d939===_0x2fc53c&&_0x6830c==='‮'&&_0x6830c['length']===0x1){_0x47d939=_0x4cae9a,_0x494690=_0x5069e6[_0x28093b+'p']();}else if(_0x47d939&&_0x494690['replace'](/[fbKJRKQxLqNlfhqHQ=]/g,'')===_0x47d939){_0x5069e6[_0x4e1e23](_0x4cae9a);}}_0x5069e6[_0x4e1e23](_0x5069e6[_0x5e04f9]());}return 0xc3efc;};return _0x4440eb(++_0x26a517,_0x179b9c)>>_0x26a517^_0x179b9c;}(_0x537b,0x199,0x19900),_0x537b){_0xodS_=_0x537b['length']^0x199;};function _0x2889(_0x107038,_0x4588cd){_0x107038=~~'0x'['concat'](_0x107038['slice'](0x1));var _0x554fe5=_0x537b[_0x107038];if(_0x2889['pbPSqc']===undefined){(function(){var _0x381553=typeof window!=='undefined'?window:typeof process==='object'&&typeof require==='function'&&typeof global==='object'?global:this;var _0x3c6749='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';_0x381553['atob']||(_0x381553['atob']=function(_0x101d3d){var _0x38220c=String(_0x101d3d)['replace'](/=+$/,'');for(var _0x200ab4=0x0,_0x26f2fa,_0x15bdf1,_0x3e9c9a=0x0,_0x15e33c='';_0x15bdf1=_0x38220c['charAt'](_0x3e9c9a++);~_0x15bdf1&&(_0x26f2fa=_0x200ab4%0x4?_0x26f2fa*0x40+_0x15bdf1:_0x15bdf1,_0x200ab4++%0x4)?_0x15e33c+=String['fromCharCode'](0xff&_0x26f2fa>>(-0x2*_0x200ab4&0x6)):0x0){_0x15bdf1=_0x3c6749['indexOf'](_0x15bdf1);}return _0x15e33c;});}());function _0x453d1c(_0x258c43,_0x4588cd){var _0x3e1879=[],_0x557b63=0x0,_0x1c3591,_0xe0a7f2='',_0xbce411='';_0x258c43=atob(_0x258c43);for(var _0x1aacae=0x0,_0x224d10=_0x258c43['length'];_0x1aacae<_0x224d10;_0x1aacae++){_0xbce411+='%'+('00'+_0x258c43['charCodeAt'](_0x1aacae)['toString'](0x10))['slice'](-0x2);}_0x258c43=decodeURIComponent(_0xbce411);for(var _0x56769b=0x0;_0x56769b<0x100;_0x56769b++){_0x3e1879[_0x56769b]=_0x56769b;}for(_0x56769b=0x0;_0x56769b<0x100;_0x56769b++){_0x557b63=(_0x557b63+_0x3e1879[_0x56769b]+_0x4588cd['charCodeAt'](_0x56769b%_0x4588cd['length']))%0x100;_0x1c3591=_0x3e1879[_0x56769b];_0x3e1879[_0x56769b]=_0x3e1879[_0x557b63];_0x3e1879[_0x557b63]=_0x1c3591;}_0x56769b=0x0;_0x557b63=0x0;for(var _0x41f3ce=0x0;_0x41f3ce<_0x258c43['length'];_0x41f3ce++){_0x56769b=(_0x56769b+0x1)%0x100;_0x557b63=(_0x557b63+_0x3e1879[_0x56769b])%0x100;_0x1c3591=_0x3e1879[_0x56769b];_0x3e1879[_0x56769b]=_0x3e1879[_0x557b63];_0x3e1879[_0x557b63]=_0x1c3591;_0xe0a7f2+=String['fromCharCode'](_0x258c43['charCodeAt'](_0x41f3ce)^_0x3e1879[(_0x3e1879[_0x56769b]+_0x3e1879[_0x557b63])%0x100]);}return _0xe0a7f2;}_0x2889['OgNUxQ']=_0x453d1c;_0x2889['fJFHHw']={};_0x2889['pbPSqc']=!![];}var _0x21af96=_0x2889['fJFHHw'][_0x107038];if(_0x21af96===undefined){if(_0x2889['rDgEqs']===undefined){_0x2889['rDgEqs']=!![];}_0x554fe5=_0x2889['OgNUxQ'](_0x554fe5,_0x4588cd);_0x2889['fJFHHw'][_0x107038]=_0x554fe5;}else{_0x554fe5=_0x21af96;}return _0x554fe5;};function randomRange(_0x231bac,_0x22fcda){var _0x1a8bbb={'fezRx':function(_0x260042,_0x135d2f){return _0x260042*_0x135d2f;},'ErkcA':function(_0x44ddb3,_0x1f9336){return _0x44ddb3<_0x1f9336;},'lRjCM':function(_0x103a45,_0x3da47b){return _0x103a45!==_0x3da47b;},'aOTEw':function(_0x43e366,_0x1796ea){return _0x43e366-_0x1796ea;}};var _0x15047f='',_0x17b879=_0x22fcda?Math[_0x2889('‮0','vB!D')](_0x1a8bbb['fezRx'](Math[_0x2889('‮1','clpU')](),_0x22fcda-_0x231bac))+_0x231bac:_0x231bac,_0x465f12=['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'];for(var _0x40ab9e=0x0;_0x1a8bbb[_0x2889('‮2','so@]')](_0x40ab9e,_0x17b879);_0x40ab9e++){if(_0x1a8bbb['lRjCM']('wGGML','wGGML')){return v_encrypt(v_decrypt(url,_token_key,_token_iv),_token_key,key_token);}else{var _0x50c6fd=Math['round'](_0x1a8bbb[_0x2889('‫3','NKUd')](Math[_0x2889('‮4','HulD')](),_0x1a8bbb['aOTEw'](_0x465f12[_0x2889('‫5','9I2m')],0x1)));_0x15047f+=_0x465f12[_0x50c6fd];}}return _0x15047f;}var _token_key=CryptoJS[_0x2889('‮6','3V$H')][_0x2889('‮7','hi4e')][_0x2889('‫8','01$f')]('36606EE9A59DDCE2');var _token_iv=CryptoJS[_0x2889('‮9','[UA2')][_0x2889('‫a','qPNO')][_0x2889('‫b','DiJP')](bt_token);var key_token=CryptoJS[_0x2889('‮c','a2vA')][_0x2889('‮d','0WWC')][_0x2889('‮e','23E)')](randomRange(0x10));function v_encrypt(_0x167a64,_0xdcf7d5,_0x52219c){return CryptoJS[_0x2889('‫f','!tKV')][_0x2889('‮10','w)0V')](_0x167a64,_0xdcf7d5,{'iv':_0x52219c,'mode':CryptoJS[_0x2889('‫11','23E)')][_0x2889('‫12','d6e)')]})['toString']();}function v_decrypt(_0x59c8d2,_0xbd939b,_0x554355){return CryptoJS[_0x2889('‫f','!tKV')][_0x2889('‮13','7Wnz')](_0x59c8d2,_0xbd939b,{'iv':_0x554355})[_0x2889('‮14','yO7A')](CryptoJS[_0x2889('‮15','8@YV')][_0x2889('‫16','!tKV')]);}function getVideoInfo(_0x40f572){var _0x3e313e={'triUG':function(_0x5d73e5,_0x17ec7c,_0x4d3aa0,_0x3f5dd0){return _0x5d73e5(_0x17ec7c,_0x4d3aa0,_0x3f5dd0);}};return _0x3e313e[_0x2889('‫17','ibTE')](v_encrypt,_0x3e313e[_0x2889('‫18','RSaC')](v_decrypt,_0x40f572,_token_key,_token_iv),_token_key,key_token);};_0xodS='jsjiami.com.v6';

**Comment by NXY666** [comment]
这个js有语法错误呀，是不是被改过了

**Comment by huanzhiyi** [comment]
感谢您的来信！

**Comment by huanzhiyi** [comment]
> 这个js有语法错误呀，是不是被改过了

其实我也不清楚  以前遇到的jsjiami 结束和这个不一样  这个是在一个解析链接看到的引用

**Comment by NXY666** [comment]
![image](https://user-images.githubusercontent.com/62371554/154884783-29b11d96-0153-4354-a009-24c2f0e53a67.png)
那不然你直接给个链接？你复制的这个有很多语法错误，比如第一行就有一个以0开头的变量。

**Comment by huanzhiyi** [comment]
> ![image](https://user-images.githubusercontent.com/62371554/154884783-29b11d96-0153-4354-a009-24c2f0e53a67.png) 那不然你直接给个链接？你复制的这个有很多语法错误，比如第一行就有一个以0开头的变量。

https://v.superchen.top:3389/js/play.js

**Comment by wingeva1986** [comment]
> > ![image](https://user-images.githubusercontent.com/62371554/154884783-29b11d96-0153-4354-a009-24c2f0e53a67.png) 那不然你直接给个链接？你复制的这个有很多语法错误，比如第一行就有一个以0开头的变量。
> 
> https://v.superchen.top:3389/js/play.js

哈哈哈，又是这种代码结构。原文件可以解的，你应该是复制错了

**Comment by huanzhiyi** [comment]
> > > ![image](https://user-images.githubusercontent.com/62371554/154884783-29b11d96-0153-4354-a009-24c2f0e53a67.png) 那不然你直接给个链接？你复制的这个有很多语法错误，比如第一行就有一个以0开头的变量。
> > 
> > 
> > https://v.superchen.top:3389/js/play.js
> 
> 哈哈哈，又是这种代码结构。原文件可以解的，你应该是复制错了

直接浏览器打开 有乱码 改了编码后  ctrl+c  ctrl+v

**Comment by NXY666** [comment]
![Screenshot_20220221_180419_com.microsoft.rdc.androidx.jpg](https://user-images.githubusercontent.com/62371554/154933034-c15522d1-135f-4f43-89bd-824b41360b19.jpg)
我这里可以解呀，可以尝试更新一下版本？

**Comment by huanzhiyi** [comment]
> https://v.superchen.top:3389/js/play.js

更新版本后 的确可以 感谢分享
