### ISSUE TITLE
这个js的输出几乎没解密

### ISSUE THREAD

**Issue by wingeva1986** [NXY666/JsjiamiV6-Decryptor#8]
https://chaxun.truechat365.com/Play/Js/play.min.js
文件中间那段抠出来输入，\x之类的16进制也没解出来

**Comment by NXY666** [comment]
\x的加密已经在写了。

**Comment by AmamiyaRain** [comment]
> \x的加密已经在写了。

能不能写快点

**Comment by NXY666** [comment]
来，你写😒


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月22日(周二) 下午4:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NXY666/JsjiamiV6-Decryptor] 这个js的输出几乎没解密 (Issue #8)




  
\x的加密已经在写了。
  
能不能写快点
 
&mdash;

**Comment by NXY666** [comment]
这个js有点特殊，预处理函数中有一段不知道在干啥，我找个时间好好研究研究。
我自己加密弄不出这个效果，不知道是开了什么。

**Comment by NXY666** [comment]
新版本兼容了这种类型的验证函数，但是js中有一处中途穿插了反格式化验证的内容，导致识别出错，这也是我第一次遇到，暂时没有解决办法，现在就只能手动去掉这一段内容进行解密。
这是去除后进行解密的结果（已格式化）：
OQ0Q0();
function OQ0Q0() {
	$.cookie('uuid', Vkey + '-' + Key + '-' + Sign + '-' + Token);
	var QQOQ0 = (Vkey + '-' + Key + '-' + Sign + '-' + Token);
	var Q0QO0 = (Key1 + '-' + Sign1 + '-' + Token1);
	$.cookie('BAIDUID', $.md5(QQOQ0).toUpperCase());
	$.cookie('BAIDUSID', $.md5(Q0QO0).toUpperCase());
	var O00O0 = XXTEA.encryptToBase64(QQOQ0 + Q0QO0 + Key2 + Sign2 + Token2, Host + Domain + Time);
	if (isios) {
		var O0Q0QO = '1';
	} else {
		var O0Q0QO = '0';
	}
	if (isiPad) {
		var O00OOQ = '1';
	} else {
		var O00OOQ = '0';
	}
	var QOOOO0 = {
		'url': Vurl, 'wap': O00OOQ, 'ios': O0Q0QO, 'host': Host, 'referer': Ref, 'time': Time, 'key': Key, 'key1': Key1,
		'sign': Sign, 'sign1': Sign1, 'token': Token, 'token1': Token1
	};
	Ckey = AES_CBC(JSON.stringify(QOOOO0), $.md5(O00O0));
	var O00OOO = {'ckey': ('110#' + Base64.encode(Ckey))};
	DATA = Object.assign(QOOOO0, O00OOO);
	var QOO0QO = TSTKC(DATA);
	iplist = returnCitySN.cip.split('.');
	var QQQO0Q = (iplist[0] + '.' + iplist[1] + '.000.000');
	var QQQOQQ = ('?ver=' + Version + '&timestamp=' + Time + '&appkey=' + $.md5(Host));
	$.ajax({
		'type': 'post', 'url': (Api + '/Api.php' + QQQOQQ), 'dataType': 'json', 'headers': {
			'Vkey': Vkey, 'Ipmd5': $.md5(QQQO0Q), 'Version': Version, 'Access-Token0': QQOQ0, 'Access-Token1': Q0QO0,
			'Access-Token2': O00O0, 'Access-Token3': QOO0QO
		}, 'data': DATA, 'success': function (QQQO0O) {
			if (QQQO0O.status == 1) {
				if ($.md5(QQQO0Q) == QQQO0O.ipmd5) {
					var O00O0O = QQQO0O.ipmd5;
				} else {
					var O00O0O = $.md5(returnCitySN.cip);
				}
				data = QQQO0O.data;
				jmdata = AES_CBC_DE(data, $.md5(QQQO0O.appkey + O00O0O));
				info = JSON.parse(jmdata);
				var O0Q0QQ = decode_url(info.url, $.md5(Host + Token));
				info.url = decodeURIComponent(O0Q0QQ);
				if (PlayConfig.Route) {
					var O0Q00Q = false;
					Routes = PlayConfig.Route.split('|');
					for (var O0QOO0 = 0; O0QOO0 < Routes.length; O0QOO0++) {
						if (info.url.indexOf(Routes[O0QOO0]) != -1) {
							O0Q00Q = true;
							break;
						} else {
							O0Q00Q = false;
						}
					}
					if (O0Q00Q) {
						$('head').append('<meta name="referrer" content="no-referrer">');
					} else {
						$('head').append('<meta name="referrer" content="strict-origin-when-cross-origin">');
					}
				} else {
					$('head').append('<meta name="referrer" content="strict-origin-when-cross-origin">');
				}
				if (info.type == 'url') {
					$('#video').html('<iframe id="video" scrolling="no" allowtransparency="true" src="' + info.url + '" width="100%" height="100%" style="background: #000000" frameborder="0" border="0" marginwidth="0" marginheight="0" allowfullscreen="allowfullscreen" mozallowfullscreen="mozallowfullscreen" msallowfullscreen="msallowfullscreen" oallowfullscreen="oallowfullscreen" webkitallowfullscreen="webkitallowfullscreen"></iframe>');
				} else {
					play(info);
				}
			} else if (PlayConfig.Online == '1') {
				$('.tips').text(QQQO0O.data.msg);
				$('#video').show();
				setTimeout(function () {
					$('#loading').hide();
					$('#video').html('<iframe frameborder=0 marginheight=0 marginwidth=0 scrolling=no src="' + PlayConfig.Ather + PlayConfig.Url + '" width="100%" height="100%" allowfullscreen="true"></iframe>');
				}, 3000);
			} else {
				$('.timeout').text(QQQO0O.data.msg);
				$('#video').show();
			}
		}
	});
};
OＯ0$ = 'jsjiami.com.v6';

**Comment by wingeva1986** [comment]
666
