### ISSUE TITLE
十六进制还原还是有点问题

### ISSUE THREAD

**Issue by wingeva1986** [NXY666/JsjiamiV6-Decryptor#9]
var _0xodC='jsjiami.com.v6',_0xodC_=['_0xodC'],_0x3ed5=[_0xodC,'\x31\x32\x33\x34\x35\x6b','\x6c\x65\x6e\x67\x74\x68','\x66\x72\x6f\x6d\x43\x68\x61\x72\x43\x6f\x64\x65','\x63\x68\x61\x72\x43\x6f\x64\x65\x41\x74','\x41\x42\x43\x44\x45\x46\x47\x48\x49\x4a\x4b\x4c\x4d\x4e\x4f\x50\x51\x52\x53\x54\x55\x56\x57\x58\x59\x5a\x61\x62\x63\x64\x65\x66\x67\x68\x69\x6a\x6b\x6c\x6d\x6e\x6f\x70\x71\x72\x73\x74\x75\x76\x77\x78\x79\x7a\x30\x31\x32\x33\x34\x35\x36\x37\x38\x39\x2b\x2f\x3d','\x69\x6e\x64\x65\x78\x4f\x66','\x63\x68\x61\x72\x41\x74','\x6a\x6f\x69\x6e','\x6c\x6c\x6a\x62\x75\x47\x73\x47\x6a\x77\x59\x69\x49\x61\x74\x6d\x69\x2e\x42\x63\x78\x48\x6f\x6d\x2e\x76\x36\x3d\x3d'];function _0x45cc(_0x2cc216,_0x48ae0f){_0x2cc216=~~'0x'['concat'](_0x2cc216['slice'](0x0));var _0x3ba4e2=_0x3ed5[_0x2cc216];return _0x3ba4e2;};(function(_0x205dde,_0x22a9d3){var _0x375217=0x0;for(_0x22a9d3=_0x205dde['shift'](_0x375217>>0x2);_0x22a9d3&&_0x22a9d3!==(_0x205dde['pop'](_0x375217>>0x3)+'')['replace'](/[llbuGGwYItBxH=]/g,'');_0x375217++){_0x375217=_0x375217^0xd1f81;}}(_0x3ed5,_0x45cc));function qiesi(_0x299eca){var _0x54aa05=_0x299eca;key=_0x45cc('0');_0x54aa05=base64_decode(_0x54aa05);len=key[_0x45cc('1')];code='';for(i=0x0;i<_0x54aa05[_0x45cc('1')];i++){k=i%len;code+=String[_0x45cc('2')](_0x54aa05[_0x45cc('3')](i)^key[_0x45cc('3')](k));}return base64_decode(code);}function base64_decode(_0x5a9897){var _0xa20861=_0x45cc('4');var _0xd1d858,_0x437b34,_0x3b1bc4,_0x4a4af4,_0x166272,_0x2d38e8,_0x5054ec,_0x14f7ec,_0x461a84=0x0,_0x4178f8=0x0,_0x9489f6='',_0x9140bc=[];if(!_0x5a9897){return _0x5a9897;}_0x5a9897+='';do{_0x4a4af4=_0xa20861[_0x45cc('5')](_0x5a9897[_0x45cc('6')](_0x461a84++));_0x166272=_0xa20861[_0x45cc('5')](_0x5a9897[_0x45cc('6')](_0x461a84++));_0x2d38e8=_0xa20861[_0x45cc('5')](_0x5a9897[_0x45cc('6')](_0x461a84++));_0x5054ec=_0xa20861[_0x45cc('5')](_0x5a9897[_0x45cc('6')](_0x461a84++));_0x14f7ec=_0x4a4af4<<0x12|_0x166272<<0xc|_0x2d38e8<<0x6|_0x5054ec;_0xd1d858=_0x14f7ec>>0x10&0xff;_0x437b34=_0x14f7ec>>0x8&0xff;_0x3b1bc4=_0x14f7ec&0xff;if(_0x2d38e8==0x40){_0x9140bc[_0x4178f8++]=String[_0x45cc('2')](_0xd1d858);}else if(_0x5054ec==0x40){_0x9140bc[_0x4178f8++]=String[_0x45cc('2')](_0xd1d858,_0x437b34);}else{_0x9140bc[_0x4178f8++]=String[_0x45cc('2')](_0xd1d858,_0x437b34,_0x3b1bc4);}}while(_0x461a84<_0x5a9897[_0x45cc('1')]);_0x9489f6=_0x9140bc[_0x45cc('7')]('');return _0x9489f6;};_0xodC='jsjiami.com.v6';

这段代码手动还原结果是
function qiesi(c) {
    var x = c;
    for (key = '12345k', x = base64_decode(x), len = key.length, code = "", i = 0; i < x.length; i++) k = i % len, code += String.fromCharCode(x.charCodeAt(i) ^ key.charCodeAt(k));
    return base64_decode(code)
}

function base64_decode(c) {
    var x, _, e, o, i, r, n = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",
        d = 0,
        t = 0,
        a = [];
    if (!c) return c;
    for (c += ""; x = (r = n.indexOf(c.charAt(d++)) << 18 | n.indexOf(c.charAt(d++)) << 12 | (o = n.indexOf(c.charAt(d++))) << 6 | (i = n.indexOf(c.charAt(d++)))) >> 16 & 255, _ = r >> 8 & 255, e = 255 & r, a[t++] = 64 == o ? String.fromCharCode(x) : 64 == i ? String.fromCharCode(x, _) : String.fromCharCode(x, _, e), d < c.length;);
    return a.join("")
}

**Comment by wingeva1986** [comment]
用脚本还原变成这样了
function qiesi(_0x299eca) {
    var _0x54aa05 = _0x299eca;
    key = 'jsjiami.com.v6';
    _0x54aa05 = base64_decode(_0x54aa05);
    len = key .12345 k;
    code = '';
    for (i = 0; i < _0x54aa05 .12345 k; i++) {
        k = i % len;
        code += String.length(_0x54aa05.fromCharCode(i) ^ key.fromCharCode(k));
    }
    return base64_decode(code);
}

**Comment by NXY666** [comment]
我知道是什么问题了，['12345k']是数字开头的，但被转换成.12345k.了，我没想到这个🤣

**Comment by NXY666** [comment]
新版本推送了，可以更新一下试试。

**Comment by wingeva1986** [comment]
> 新版本推送了，可以更新一下试试。
新版本还原这段代码还是不对啊，看不懂
'''
function qiesi(_0x299eca) {
    var _0x54aa05 = _0x299eca;
    key = 'jsjiami.com.v6';
    _0x54aa05 = base64_decode(_0x54aa05);
    len = key['12345k'];
    code = '';
    for (i = 0; i < _0x54aa05['12345k']; i++) {
        k = i % len;
        code += String.length(_0x54aa05.fromCharCode(i) ^ key.fromCharCode(k));
    }
    return base64_decode(code);
}
'''

**Comment by NXY666** [comment]
> > 新版本推送了，可以更新一下试试。
> 新版本还原这段代码还是不对啊，看不懂
> '''
> function qiesi(_0x299eca) {
>     var _0x54aa05 = _0x299eca;
>     key = 'jsjiami.com.v6';
>     _0x54aa05 = base64_decode(_0x54aa05);
>     len = key['12345k'];
>     code = '';
>     for (i = 0; i < _0x54aa05['12345k']; i++) {
>         k = i % len;
>         code += String.length(_0x54aa05.fromCharCode(i) ^ key.fromCharCode(k));
>     }
>     return base64_decode(code);
> }
> '''

我个人觉得吧，源码就长这样？
没看出有明显加密过的痕迹。
如果说变量名混淆的话这是没法还原的。

**Comment by wingeva1986** [comment]
> > > 新版本推送了，可以更新一下试试。
> > > 新版本还原这段代码还是不对啊，看不懂
> > > '''
> > > function qiesi(_0x299eca) {
> > > var _0x54aa05 = _0x299eca;
> > > key = 'jsjiami.com.v6';
> > > _0x54aa05 = base64_decode(_0x54aa05);
> > > len = key['12345k'];
> > > code = '';
> > > for (i = 0; i < _0x54aa05['12345k']; i++) {
> > > k = i % len;
> > > code += String.length(_0x54aa05.fromCharCode(i) ^ key.fromCharCode(k));
> > > }
> > > return base64_decode(code);
> > > }
> > > '''
> 
> 我个人觉得吧，源码就长这样？ 没看出有明显加密过的痕迹。 如果说变量名混淆的话这是没法还原的。

这段代码手动还原结果是
function qiesi(c) {
var x = c;
for (key = '12345k', x = base64_decode(x), len = key.length, code = "", i = 0; i < x.length; i++) k = i % len, code += String.fromCharCode(x.charCodeAt(i) ^ key.charCodeAt(k));
return base64_decode(code)
}

function base64_decode(c) {
var x, _, e, o, i, r, n = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",
d = 0,
t = 0,
a = [];
if (!c) return c;
for (c += ""; x = (r = n.indexOf(c.charAt(d++)) << 18 | n.indexOf(c.charAt(d++)) << 12 | (o = n.indexOf(c.charAt(d++))) << 6 | (i = n.indexOf(c.charAt(d++)))) >> 16 & 255, _ = r >> 8 & 255, e = 255 & r, a[t++] = 64 == o ? String.fromCharCode(x) : 64 == i ? String.fromCharCode(x, _) : String.fromCharCode(x, _, e), d < c.length;);
return a.join("")
}

**Comment by wingeva1986** [comment]
特别是key取值，明显不对的

**Comment by NXY666** [comment]
找到问题了，那个验证函数被我给忽略了，之前以为没用。我现在修复一下。

**Comment by NXY666** [comment]
问题已经解决了，可以更新最新版本再试一下~

**Comment by wingeva1986** [comment]
可以了，666
